# .github/workflows/ci.yml
name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Usa la versión del packageManager (pnpm@9.15.9)
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm -v
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: pnpm -r test --if-present
