name: route-labels
on: issues
permissions:
  issues: write
jobs:
  route:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const i = context.payload.issue
            const title = i.title || ""
            const labels = []
            if (title.startsWith("feat(core/"))) labels.push("type:feat","area:core")
            if (title.startsWith("feat(framework/"))) labels.push("type:feat","area:framework")
            if (title.startsWith("feat(saasp/"))) labels.push("type:feat","area:saas")
            if (title.startsWith("chore(")) labels.push("type:chore")
            if (title.startsWith("docs("))  labels.push("type:docs")
            if (labels.length) {
              await github.rest.issues.addLabels({ ...context.repo, issue_number: i.number, labels })
            }
